import type { Metadata } from "next";
import { satoshi } from "./fonts";
import "./globals.css";
import { Navbar } from "./_components/navbar";
import Footer from "./_components/footer";

export const metadata: Metadata = {
  title: "Ali Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="language" content="Uzbek" />
        <meta name="google-translate-customization" content="auto-translate" />
        <meta property="og:locale" content="uz_UZ" />
      </head>
      <body className={`${satoshi.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
